# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 14:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('usersManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='pw_hash',
            new_name='password',
        ),
    ]
